application: yamanokikaku
version: 1
runtime: python27
api_version: 1
threadsafe: yes

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'

libraries:
- name: django
  version: "1.3"

- name: webapp2
  version: "2.5.1"

handlers:
- url: /images
  static_dir: images

- url: /(.*\.htm)
  static_files: \1
  upload: .*\.htm

- url: /(.*\.html)
  static_files: \1
  upload: .*\.html

- url: /admin/.*
  script: admin.app
  login: admin

- url: .*
  script: main.app

# eof
